### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by cielavenir**

### CODE REVIEW

**Comment by bicycle1885** [comment]
Great! That looks good, however, I cannot confirm it really works or not. I've activated AppVayor for this repository and fixed the settings (https://github.com/bicycle1885/CodecBzip2.jl/commit/07963a2076fb3371d7b3fcaa2881be1df999de97) so that we can confirm it works on a fresh Windows machine. So, could you rebase this pull request onto the current master branch and then push it again here? I think it will run AppVayor for this pull request.

**Comment by cielavenir** [comment]
Could you do this update also for Xz (and maybe Zstd, since although we don't support yet but anyway Julia 0.6 is required) ?

**Comment by bicycle1885** [comment]
Updated. Now you find a (failing) AppVeyor badge on each project page.

**Comment by cielavenir** [comment]
Eh, win64 is OK, but win32 is weird...

**Comment by bicycle1885** [comment]
Okay, let's forget win32 for a while. You can comment out a line to remove it from the AppVeyor tests: https://github.com/bicycle1885/CodecBzip2.jl/blob/a367beb463e49258d9f2f76a7dacac096f47121a/appveyor.yml#L3.

**Comment by bicycle1885** [comment]
Thank you a lot!

**Comment by bicycle1885** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/9835

**Comment by cielavenir** [comment]
So, let's see http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/noarch/mingw32-libbz2-1-1.0.6-12.8.noarch.rpm . There are bunch of BZ2_bzBuffToBuffCompress@28 stuffs. These are stdcall stuff and we will have to change calling convention on Win32 (not on Win64).

**Comment by cielavenir** [comment]
ah sorry for late reply...

**Pull request merged**
